language: ruby
rvm:
 — 2.7.1
deploy:
  provider: cloudfoundry
  api: $API_URI
  username: $USERNAME_DEPLOY
  password: $PASSWORD_DEPLOY
  organization: $ORG_NAME
  space: $SPACE_TYPE_DEVELOPMENT
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: develop
