language: ruby
rvm:
 — 2.7.1
deploy:
  edge: true
  provider: cloudfoundry
  api: $API_URI
  username: $USERNAME_STAGE
  password: $PASSWORD_STAGE
  organization: $ORG_NAME
  space: $SPACE_TYPE_STAGING
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: staging
  skip_cleanup: 'true'
    
