dist: bionic
language: ruby
rvm:
 — 2.7.1
deploy:
  edge: true
  provider: cloudfoundry
  api: $API_URI
  username: $USERNAME
  password: $PASSWORD
  organization: $ORG_NAME
  space: $SPACE_TYPE_STAGING
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: staging
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: '11'
sudo: true
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-11-postgis-2.5
  - psql -U postgres -c 'create database pmp_idam_test'
  - psql -U postgres -d pmp_idam_test -c 'create extension postgis'
script:
  - bundle exec rake db:setup
  - bundle exec rake
