language: ruby
rvm:
 — 2.7.1
deploy:
  provider: cloudfoundry
  api: $API_URI
  username: $USERNAME_STAGE
  password: $PASSWORD_STAGE
  organization: $ORG_NAME
  space: $SPACE_TYPE_TEST
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: test
