language: ruby
rvm:
 — 2.7.1
deploy:
  provider: $PROVIDER_TYPE
  api: $API_URI
  username: $USERNAME
  password: $PASSWORD
  organization: $ORG_NAME
  space: $SPACE_TYPE
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: test
  skip_cleanup: 'true'
